### PR TITLE
Branding layout

### PR DESCRIPTION
**Pull request by dstrawberrygirl**
Added a new hierarchy to switch between simulations via query parameters from the main Index page

### CODE REVIEW

**Review by pjanik — CHANGES_REQUESTED** [review]
The structure looks good to me. 👍 

The main problem is that none of the simulations seem to work (http://models-resources.concord.org/leap-motion/branch/branding-layout/index.html?simulation=labvolumepressure).

Lab-based pages have no interactive visible and Season's layout is also a bit broken. Probably CSS issues.

Also, it'd be great to remove unused pages in `/public`, all the unnecessary `main.jsx` files and update webpack config. It would totally break old links, but they'll be broken (/ outdated) anyway when we merge this change. 

It wouldn't be any problem if we could finally convince Illinois team to use production version instead of development one (/branch/master). 

@nkimball, could you ask them what URLs they use, if we can update production and ask them to use production version from now on? I guess they use development version, as production hasn't been updated for ages.

**Comment by dstrawberrygirl** [comment]
Updated the branch to remove older files - now ready for handover to @emcelroy for css tasks to fix layout issues and bring up to spec with new branding guidelines.

**Comment by pjanik** [comment]
@dstrawberrygirl, have you noticed my comment about broken models? Lab interactives are invisible and Seasons layout is a bit broken. I wouldn't expect surrounding layout to affect models themselves. Probably it's some unlucky CSS conflict.

screen shot 2017-03-20 at 23 02 08

**Comment by dstrawberrygirl** [comment]
@pjanik thanks for the feedback - I looked at this yesterday and it seems to be all related to css, since a lot of the models have their own styles. I was able to use the broken interactives by interacting with them until the hint animations faded out. @emcelroy is going to go through the css for all of the models on this branch and assist with brand-styling and correcting the hierarchy of styles to get things working again, so this branch will be a work-in-progress until that process is complete. If you think it best we can close the PR and continue work in the branch until we're ready to review for a merge.

**Comment by pjanik** [comment]
I see. PR can be open, I don't mind. I mentioned it, as I thought you wanted to merge this PR now (and it would be problematic to work on other things until those issues are fixed).

**Pull request merged**
